server {
    listen 80;
    root /usr/share/nginx/html;
    index models.html;

    location /models {
        autoindex on;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
    }
}
